const SECTIONS=window.SURVEY_SECTIONS;
const sectionByNumber=new Map(SECTIONS.map(s=>[s.number,s]));
const chapterFlow=[
 {id:'quantification',number:'01',range:'§§3–4',question:'What is uncertain?',intro:'Represent insufficient support before deciding what to do with it. Begin with token and response signals, then follow uncertainty through an agent’s interactive trajectory.',parts:['3.1','3.2','4.2','4.3','4.4']},
 {id:'calibration',number:'02',range:'§5',question:'What does confidence mean?',intro:'Align a reported signal with a specified reliability event: a correct claim, a productive action, or a successful trajectory. The target and the deployment policy both matter.',parts:['5.2','5.3','5.4']},
 {id:'utilization',number:'03',range:'§6',question:'How should behavior change?',intro:'Follow the agent loop in order. The stage is determined by where uncertainty changes behavior: constructing the state, selecting an action, adapting execution, or updating what persists.',parts:['6.3','6.4','6.5','6.6']}
];
const shortNames={'3.1':'Token-level signals','3.2':'Response-level signals','4.2':'Within-rollout quantification','4.3':'Sampling-based quantification','4.4':'Input uncertainty','5.2':'Test-time & runtime','5.3':'Training-time calibration','5.4':'Decision-oriented calibration','6.3':'State construction','6.4':'Action selection','6.5':'Execution & feedback','6.6':'State update'};
const sectionBrief={
'3.1':'Inspect the model’s local predictive distribution and internal signals before combining them into larger units of uncertainty.',
'3.1.1':'Measure divergence between predictive distributions or against a reference distribution to reveal unsupported or unstable predictions.',
'3.1.2':'Use distances in representation or gradient space to identify predictions that depart from supported regions.',
'3.1.3':'Estimate whether token representations lie in regions supported by the model’s reference data.',
'3.1.4':'Use mutual information to examine dependence between predictions and the conditioning evidence.',
'3.1.5':'Read uncertainty from token probabilities, likelihoods, and explicit uncertainty-bearing outputs.',
'3.1.6':'Summarize the spread of a predictive distribution through entropy and related token-level measures.',
'3.2':'Move from individual tokens to complete responses: agreement, semantic variation, verbal confidence, and reward-model disagreement.',
'3.2.1':'Compare multiple generations for consistency. Agreement is informative, but repeated answers can share the same error.',
'3.2.2':'Group sampled answers by meaning so that uncertainty reflects semantic alternatives rather than wording alone.',
'3.2.3':'Ask the model to express confidence or uncertainty. The resulting statement still needs its reliability checked.',
'3.2.4':'Use variation across reward models or reward estimates to characterize uncertainty in preference-based evaluation.',
'4.2':'Follow one realized trajectory. Local uncertainty can be aggregated into a process signal or propagated through dependent decisions.',
'4.2.1':'Combine local uncertainty estimates within a rollout to summarize the reliability or risk of the process.',
'4.2.2':'Track how uncertainty at an earlier decision affects the support available at later steps.',
'4.3':'Compare alternative decisions, search branches, complete rollouts, or agents. Sampling changes the object being compared and the computational cost.',
'4.4':'An instruction, tool result, memory, or observation may be ambiguous or insufficient. Interaction can sometimes remove this uncertainty before the next action.',
'5.2':'Diagnose the reliability target, learn an offline correction, and update confidence from deployment feedback. Elicitation and dependence-aware correction complement this sequence.',
'5.3':'Teach uncertainty behavior through supervision, separate expression from alignment in hybrid training, or place calibration directly in the reinforcement-learning reward.',
'5.4':'Use calibration data to construct a controlled output set, filtering rule, or delegation boundary. Conformal guarantees depend on their stated assumptions.',
'6.3':'Before choosing an action, determine whether the assembled instruction, observations, evidence, and memory support a reliable commitment.',
'6.3.1':'Detect missing or ambiguous information and decide when the current state needs clarification.',
'6.3.2':'Choose questions or evidence requests according to the information they are expected to provide.',
'6.3.3':'Repair noisy or incomplete context through selection, reorganization, retrieval, or renewed perception.',
'6.4':'Use the support available now to control commitment, allocate deliberation, and choose who should act.',
'6.4.1':'Commit, defer, abstain, or seek help according to whether the next action is sufficiently supported.',
'6.4.2':'Spend additional computation on uncertain decisions by generating alternatives, branching, or scaling deliberation.',
'6.4.3':'Compare available executors and transfer decision authority when another agent is sufficiently more reliable.',
'6.5':'Once an action produces new tool or environmental evidence, use that feedback to change the ongoing execution.',
'6.5.1':'Expand unstable transitions and allocate a finite budget between complete and partial rollouts.',
'6.5.2':'Revise active planning and search as the consequences of candidate actions become available.',
'6.5.3':'Use accumulated evidence to localize recovery or terminate a trajectory that no longer justifies continued execution.',
'6.6':'Decide how uncertainty should influence persistent beliefs, shared reasoning, delayed credit, and policy learning.',
'6.6.1':'Retain and revise uncertainty-bearing beliefs or memory so that later actions inherit the right evidence.',
'6.6.2':'Weight the influence of communicated beliefs by confidence. This subsection also contrasts calibration-only methods and disagreement-based communication.',
'6.6.3':'Construct alternative experience, identify consequential decisions, and modulate how delayed outcomes update the policy.',
'6.6.4':'Shape the learning objective to reward information gain, regulate exploration, or align confidence with successful behavior.'
};
const sid=n=>'section-'+n.replaceAll('.','-');
const subSections=n=>SECTIONS.filter(s=>s.number.startsWith(n+'.'));
function guideLink(n,text,cls=''){return `<a class="${cls}" href="#guide/${n}" data-section-link="${n}">${text}</a>`;}
function contextualPaper(id,n){const p=paperById.get(id),comparison=n==='6.6.2'&&[143,155,202,207].includes(id);return `<article class="context-paper"><span class="context-ref">[${id}]</span><div><button data-paper="${id}" class="context-title">${esc(p.title)}</button><p>${esc(p.authors.split(',').slice(0,2).join(','))}${p.authors.split(',').length>2?' et al.':''} · ${esc(p.year)}</p><div class="context-tags">${p.aliases.slice(0,2).map(a=>tag(a,'alias')).join('')}${comparison?tag('Comparison / boundary case'):''}<a href="#read/${sectionByNumber.get(n)?.page||4}">Discussed in §${n} ↗</a></div></div><button class="context-open" data-paper="${id}" aria-label="Inspect reference ${id} in section ${n}">↗</button></article>`;}
function sectionPapers(s){if(!s.refs.length)return '';return `<div class="section-papers"><div class="paper-list-label">PAPERS DISCUSSED <span>${s.refs.length}</span></div>${s.refs.slice(0,3).map(id=>contextualPaper(id,s.number)).join('')}${s.refs.length>3?`<details class="more-section-papers"><summary>Show all ${s.refs.length} papers in §${s.number}<span>+</span></summary>${s.refs.slice(3).map(id=>contextualPaper(id,s.number)).join('')}</details>`:''}</div>`;}
function guideSub(s){return `<section class="guide-subsection" id="${sid(s.number)}" data-reading-section="${s.number}"><div class="subsection-heading"><span>§${s.number}</span><h4>${esc(s.title)}</h4><a href="#read/${s.page}" aria-label="Read section ${s.number} in PDF">PDF ↗</a></div><p class="section-explanation">${esc(sectionBrief[s.number]||'Follow the discussion and its cited evidence in the original survey.')}</p>${sectionPapers(s)}</section>`;}
function guidePart(n,life,index){const s=sectionByNumber.get(n),children=subSections(n);return `<section class="guide-part" id="${sid(n)}" data-reading-section="${n}"><div class="part-header"><div><span class="part-kicker">${life==='utilization'?'STAGE 0'+(index+1):'SURVEY §'+n}</span><h3>${esc(shortNames[n]||s.title)}</h3></div><a href="#read/${s.page}">§${n} · p. ${s.page} ↗</a></div><p class="part-intro">${esc(sectionBrief[n])}</p>${children.length?`${s.refs.length?`<details class="overview-papers"><summary>Stage / section overview references · ${s.refs.length}</summary>${s.refs.map(id=>contextualPaper(id,n)).join('')}</details>`:''}${children.map(guideSub).join('')}`:sectionPapers(s)}</section>`;}
function readingIndex(){return `<aside class="reading-index"><details open><summary>On this page <span>☰</span></summary><nav aria-label="Survey section index">${chapterFlow.map(c=>`<div class="index-chapter">${guideLink(c.id,`<span>${c.number}</span>${capital(c.id)}`,'index-main')}${c.parts.map(n=>`<div class="index-branch">${guideLink(n,`<small>${n}</small>${shortNames[n]}`,'index-part')}<div class="index-children">${subSections(n).map(x=>guideLink(x.number,`<small>${x.number}</small>${esc(x.title)}`,'index-sub')).join('')}</div></div>`).join('')}</div>`).join('')}</nav><div class="index-resources"><a href="#papers">All 245 references & audit ↗</a><a href="#matrix">Method comparison · Table 4 ↗</a><a href="#read">Read the original survey ↗</a></div></details></aside>`;}
function surveyGuide(){return `<div class="reading-layout">${readingIndex()}<article class="reading-content"><header class="reading-intro"><span class="eyebrow">UNCERTAINTY IN LLM AGENTS · A COMPREHENSIVE SURVEY</span><h1>From uncertainty<br>to <em>adaptive behavior.</em></h1><p>A guided reading of the survey, with papers organized where they enter the argument.</p><div class="reading-sequence">${chapterFlow.map(c=>guideLink(c.id,`<span>${c.number}</span>${capital(c.id)}`)).join('<span class="sequence-arrow">→</span>')}</div><p class="reading-provenance">Paper placement follows citations in the numbered body sections, including background and comparison works. A paper may appear in more than one section. Introductions are editorial summaries; original reference numbers and verification records are preserved.</p></header>${chapterFlow.map(c=>`<section class="reading-chapter ${c.id}" id="${sid(c.id)}" data-reading-section="${c.id}"><header class="chapter-opening"><span class="chapter-big-number">${c.number}</span><div><span class="eyebrow">${c.range} / ${c.question}</span><h2>${capital(c.id)}</h2><p>${c.intro}</p></div></header>${c.id==='utilization'?`<div class="stage-sequence">${c.parts.map((n,i)=>guideLink(n,`<small>0${i+1}</small><span>${shortNames[n]}</span>`)).join('')}</div>`:''}${c.parts.map((n,i)=>guidePart(n,c.id,i)).join('')}<details class="chapter-context"><summary>Framing and discussion references from ${c.range}</summary>${SECTIONS.filter(s=>(c.id==='quantification'?['3','4'].includes(s.number.split('.')[0]):s.number.split('.')[0]===(c.id==='calibration'?'5':'6'))&&!c.parts.some(n=>s.number===n||s.number.startsWith(n+'.'))&&s.refs.length).map(s=>`<div class="context-reading"><h4>§${s.number} ${esc(s.title)}</h4>${sectionPapers(s)}</div>`).join('')}</details></section>`).join('')}<div class="reading-end"><p>Continue into application domains and open questions.</p><a class="btn" href="#read/38">Applications · §7 ↗</a><a class="btn" href="#read/42">Open problems · §8 ↗</a><a class="text-link" href="#papers">Explore all 245 references →</a></div></article></div>`;}
let readingScroll;
function wireReading(arg){if(readingScroll)window.removeEventListener('scroll',readingScroll);if(!$('.reading-layout'))return;if(matchMedia('(max-width:600px)').matches)$('.reading-index details').open=false;let previous='',queued=false;
 const active=n=>{if(n===previous)return;previous=n;document.querySelectorAll('[data-section-link]').forEach(a=>{const on=a.dataset.sectionLink===n||n.startsWith(a.dataset.sectionLink+'.');a.classList.toggle('reading-active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});document.querySelectorAll('.index-branch').forEach(b=>b.classList.toggle('branch-active',!!b.querySelector('.reading-active')));const link=document.querySelector('.reading-index [data-section-link="'+n+'"]'),index=$('.reading-index');if(link&&matchMedia('(min-width:601px)').matches){const a=link.getBoundingClientRect(),b=index.getBoundingClientRect();if(a.bottom>b.bottom-24)index.scrollTop+=a.bottom-b.bottom+60;else if(a.top<b.top+20)index.scrollTop-=b.top-a.top+50;}};
 const update=()=>{queued=false;let n='motivation';document.querySelectorAll('[data-reading-section]').forEach(s=>{const r=s.getBoundingClientRect();if(r.top<=130&&r.bottom>0)n=s.dataset.readingSection});active(n);};readingScroll=()=>{if(!queued){queued=true;requestAnimationFrame(update)}};window.addEventListener('scroll',readingScroll,{passive:true});const jump=arg&&document.getElementById(sid(arg));if(jump)requestAnimationFrame(()=>{let parent=jump.parentElement;while(parent){if(parent.tagName==='DETAILS')parent.open=true;parent=parent.parentElement;}jump.scrollIntoView({block:'start'});update()});else update();}
function groupedResults(rows){const allowed=new Set(rows.map(p=>p.id));const groups=[['Quantification · §§3–4',['3','4']],['Calibration · §5',['5']],['Utilization · §6',['6']],['Introduction, scope & taxonomy · §§1–2',['1','2']],['Application domains · §7',['7']],['Open problems · §8',['8']]];return groups.map(([title,chapters])=>{const sections=SECTIONS.filter(s=>chapters.includes(s.number.split('.')[0])&&s.refs.some(id=>allowed.has(id)));const count=new Set(sections.flatMap(s=>s.refs.filter(id=>allowed.has(id)))).size;if(!count)return '';return `<details class="library-section-group"><summary>${title}<small>${count} references</small></summary>${sections.map(s=>`<details class="library-subgroup"><summary>§${s.number} ${esc(s.title)} · ${s.refs.filter(id=>allowed.has(id)).length}</summary><p class="provenance"><a href="#read/${s.page}">View this discussion in the survey ↗</a></p>${s.refs.filter(id=>allowed.has(id)).map(id=>paperRow(paperById.get(id))).join('')}</details>`).join('')}</details>`;}).join('');}
